version: '3'

services:
    teachteam-mysql-db:
        image: mysql:8.0
        container_name: teachteam-mysql-db
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_PASSWORD: 12345